# Generated by Django 5.1.3 on 2024-12-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_telegram', '0002_remove_telegramuser_token_telegramuser_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramauthsession',
            name='created',
            field=models.DateTimeField(default=None),
        ),
    ]
